### ISSUE TITLE
Issues with sites using Emoji Favicon Toolkit

### ISSUE THREAD

**Issue by eligrey** [bpevs/favioli#49]
Favioli resets the favicon to the default ServiceWorker-cached /favicon.ico on sites that use Emoji Favicon Toolkit, such as <https://eligrey.com>.

I use EFT here: <https://eligrey.com/blog/wp-content/themes/eligrey.com/js/favicon.js>

Expected results: Favicon is set to one of: 👨‍🔬 👨‍💻 👨‍🚀 🤯 🤖 ⚡ 🌧️ 🚀 💻 🧠 👻 📜 ☄️ 🛸 🌌 🌠 🛰️ ✨ 🔥 ✈️ ☕️ 🍕 🐱‍💻 and changes to 💬 whenever any input elements get modified.

Observed results: Favicon is set to 🛠️ (default favicon) and never changes.

**Comment by ivebencrazy** [comment]
Sorry for slowest turnaround ever.  This should be fixed when I release [Favioli 2.00](https://github.com/ivebencrazy/favioli/compare/feature/2.00).  Will close this issue at that time.

Fix is basically to actually check for existing favicon links instead of relying on browser to override favicon in preferred order: https://github.com/ivebencrazy/favioli/commit/d3de7f114cc18904a3ac26b98bf8f8bca02a5d72

Note: this will effect autofill specifically (the feature that fills in missing favicon). If a user is specifically trying to override the favicon of a website using Emoji Favicon Toolkit, Favioli will side on the user preference.  

Video of fix:

https://user-images.githubusercontent.com/8182843/170582000-e1eea428-34ca-4340-8e4b-dc1b1e087a73.mov

**Comment by Gitoffthelawn** [comment]
When v2.00 is released, will it support holographic emoji?  I hear they will be the new cool thing in about a decade, so the timing should be about right. 😆 🤣 🤣 🤣  😸 

I'm just teasin' ya... take your time... this extension is like a fine wine, except I can afford this extension. 🍷 🤣

**Comment by ivebencrazy** [comment]
🗿 

Haha the difference is that now I've actually stopped procrastinating on it 😛. Almost feature even with 1.00 now... Only hard thing left is re-implementing the favicon selector ui, since I want to add support for replacing with custom images right off the bat.

**Comment by Gitoffthelawn** [comment]
> Haha the difference is that now I've actually stopped procrastinating on it stuck_out_tongue. Almost feature even with 1.00 now... Only hard thing left is re-implementing the favicon selector ui, since I want to have the support for custom images right off the bat.

Sounds real good.  Take your time.  Have fun with it.
