### ISSUE TITLE
Add ability to reset bookmark favicon to site's default

### ISSUE THREAD

**Issue by Gitoffthelawn** [bpevs/favioli#52]
See our discussion in https://github.com/ivebencrazy/favioli/issues/50

**Comment by bpevs** [comment]
I suspect this has something to do with how FF caches favicons.  In Chrome, it looks like the icon is whatever the last pageload resulted in.  In Firefox, something else is happening...

In the other thread, you had mentioned this project re bookmarks:
https://github.com/tanwald/checkmarks

Another one that might be worth looking at is:
https://github.com/jscher2000/cache-favicons-for-bookmarks-extension

I do think I want to approach the bookmarking aspect of this, but more along the lines of "I want the bookmark favicon to match the tab favicon" , and avoid situations like this:

# Firefox, OSX
<img width="746" alt="Screen Shot 2022-07-02 at 11 01 00 AM" src="https://user-images.githubusercontent.com/8182843/177011608-1cfa7dc8-e5bc-4f35-92fe-44672f7e110d.png">

# Chrome OSX
<img width="612" alt="Screen Shot 2022-07-02 at 11 03 15 AM" src="https://user-images.githubusercontent.com/8182843/177011609-a8326821-125e-4bb2-8e3a-e84f39bb7940.png">

**Comment by Gitoffthelawn** [comment]
At one point, I thought I *completely* understood how Firefox handles favicons.  I created a bunch of test cases, and the results matched my understanding.  Yea.  Then things started to happen with favicons that I couldn't quite explain, and I realized that either things changed in Firefox, or my understanding wasn't quite right.  Then life happened, and I didn't have time to figure it all out. ;)

**Comment by bpevs** [comment]
Soooo looked into this a bit more... Don't think I can fix this in Favioli.  More of a Firefox issue.

My previous confidence was based on the existence of prior art, but I can't seem to get either [Checkmarks](https://github.com/tanwald/checkmarks) or [cache-favicons](https://github.com/jscher2000/cache-favicons-for-bookmarks-extension) to work for either Favioli or even just other favicon updates. Re Checkmarks: "WebExtensions cannot delete invalid favicons. You have to manually delete favicons.sqlite in your profile folder first." Otherwise, these look to just be extensions that open websites.

This could be achieved via a script or something, but this seems to be a problem that affects standard favicons as well, and is out of scope for a web extension.

If something changes, I can re-open, but otherwise this seems unfixable from this extension.
