### ISSUE TITLE
Change favicon to any custom favicon not just to emojis

### ISSUE THREAD

**Issue by michaelkolesidis** [bpevs/favioli#55]
It would be great if we could change a website's favicon to any image of our choice not just to a set of emojis.

**Comment by ivebencrazy** [comment]
^ this is definitely on my radar.  It's slightly weirder to add than you'd expect, because I originally built Favioli around "emojis" instead of around "favicons"... which was kind of dumb.  But this is the first thing I'm addressing in a round of code changes I'm making.

Oh fyi also, sorry this project was dead for a little while, while I was working on music stuff.

I'm still not 100% back and engaged, but I'm getting back into personal coding projects now.  So changes should be coming in the not-so-distant future.  :+1:

**Comment by Gitoffthelawn** [comment]
Great to hear.  Have fun, whether it's music or coding... :)

**Comment by deadmouse** [comment]
@ivebencrazy estimated date for this future? :)

**Comment by ivebencrazy** [comment]
I'm almost certain this will be finished before end of June.

**Comment by bpevs** [comment]
^ Feature complete!  Have a couple minor cleanup and validation/error message things to do, but it's basically there!

I made an unfortunate comment edit haha. I think it'll probably be FINISHED in the next 2 days (and available as crx on the releases page), but I anticipate that it won't be RELEASED on ff and chrome stores for a little longer after that, depending on if those app stores do a manual review (which they do sometimes for large code changes like this).

**Comment by bpevs** [comment]
2.0.0 is now available on Firefox!
https://addons.mozilla.org/en-US/firefox/addon/favioli/

Pending Chrome...

**Comment by bpevs** [comment]
2.0.0 was not accepted by Chrome webstore, so it took a little longer, but 2.0.1 is now live on Chrome!
So this feature is now available in Firefox and in Chromium-based browsers (Chrome, Edge, etc)

Chrome:
https://chrome.google.com/webstore/detail/favioli/pnoookpoipfmadlpkijnboajfklplgbe

Firefox:
https://addons.mozilla.org/en-US/firefox/addon/favioli/
